package com.oracle.cars.model;

import java.io.Serializable;

/**
 * Car 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Car implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** carid. */
	private String carid;

	/** color. */
	private String color;

	/** cartype. */
	private String cartype;

	/** jili. */
	private Integer jili;

	/**
	 * 僐儞僗僩儔僋僞.
	 */
	public Car() {
	}

	/**
	 * carid 傪愝掕偟傑偡.
	 * 
	 * @param carid
	 *            carid
	 */
	public void setCarid(String carid) {
		this.carid = carid;
	}

	/**
	 * carid 傪庢摼偟傑偡.
	 * 
	 * @return carid
	 */
	public String getCarid() {
		return this.carid;
	}

	/**
	 * color 傪愝掕偟傑偡.
	 * 
	 * @param color
	 *            color
	 */
	public void setColor(String color) {
		this.color = color;
	}

	/**
	 * color 傪庢摼偟傑偡.
	 * 
	 * @return color
	 */
	public String getColor() {
		return this.color;
	}

	/**
	 * cartype 傪愝掕偟傑偡.
	 * 
	 * @param cartype
	 *            cartype
	 */
	public void setCartype(String cartype) {
		this.cartype = cartype;
	}

	/**
	 * cartype 傪庢摼偟傑偡.
	 * 
	 * @return cartype
	 */
	public String getCartype() {
		return this.cartype;
	}

	/**
	 * jili 傪愝掕偟傑偡.
	 * 
	 * @param jili
	 *            jili
	 */
	public void setJili(Integer jili) {
		this.jili = jili;
	}

	/**
	 * jili 傪庢摼偟傑偡.
	 * 
	 * @return jili
	 */
	public Integer getJili() {
		return this.jili;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((carid == null) ? 0 : carid.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Car other = (Car) obj;
		if (carid == null) {
			if (other.carid != null) {
				return false;
			}
		} else if (!carid.equals(other.carid)) {
			return false;
		}

		return true;
	}

}
