package com.oracle.cars.model;

import java.io.Serializable;

/**
 * Sell 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Sell implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** name. */
	private String name;

	/** sellid. */
	private String sellid;

	/** carid. */
	private String carid;

	/** selprice. */
	private Integer selprice;

	/**
	 * 僐儞僗僩儔僋僞.
	 */
	public Sell() {
	}

	/**
	 * name 傪愝掕偟傑偡.
	 * 
	 * @param name
	 *            name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * name 傪庢摼偟傑偡.
	 * 
	 * @return name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * sellid 傪愝掕偟傑偡.
	 * 
	 * @param sellid
	 *            sellid
	 */
	public void setSellid(String sellid) {
		this.sellid = sellid;
	}

	/**
	 * sellid 傪庢摼偟傑偡.
	 * 
	 * @return sellid
	 */
	public String getSellid() {
		return this.sellid;
	}

	/**
	 * carid 傪愝掕偟傑偡.
	 * 
	 * @param carid
	 *            carid
	 */
	public void setCarid(String carid) {
		this.carid = carid;
	}

	/**
	 * carid 傪庢摼偟傑偡.
	 * 
	 * @return carid
	 */
	public String getCarid() {
		return this.carid;
	}

	/**
	 * selprice 傪愝掕偟傑偡.
	 * 
	 * @param selprice
	 *            selprice
	 */
	public void setSelprice(Integer selprice) {
		this.selprice = selprice;
	}

	/**
	 * selprice 傪庢摼偟傑偡.
	 * 
	 * @return selprice
	 */
	public Integer getSelprice() {
		return this.selprice;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((sellid == null) ? 0 : sellid.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Sell other = (Sell) obj;
		if (sellid == null) {
			if (other.sellid != null) {
				return false;
			}
		} else if (!sellid.equals(other.sellid)) {
			return false;
		}

		return true;
	}

}
