package com.oracle.cars.model;

import java.io.Serializable;
import java.sql.Blob;

/**
 * servlet 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Servlet implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** shouhou. */
	private String shouhou;

	/** baoxian. */
	private String baoxian;

	/** weixiu. */
	private Blob weixiu;

	/** tuihuan. */
	private String tuihuan;

	/**
	 * 僐儞僗僩儔僋僞.
	 */
	public Servlet() {
	}

	/**
	 * shouhou 傪愝掕偟傑偡.
	 * 
	 * @param shouhou
	 *            shouhou
	 */
	public void setShouhou(String shouhou) {
		this.shouhou = shouhou;
	}

	/**
	 * shouhou 傪庢摼偟傑偡.
	 * 
	 * @return shouhou
	 */
	public String getShouhou() {
		return this.shouhou;
	}

	/**
	 * baoxian 傪愝掕偟傑偡.
	 * 
	 * @param baoxian
	 *            baoxian
	 */
	public void setBaoxian(String baoxian) {
		this.baoxian = baoxian;
	}

	/**
	 * baoxian 傪庢摼偟傑偡.
	 * 
	 * @return baoxian
	 */
	public String getBaoxian() {
		return this.baoxian;
	}

	/**
	 * weixiu 傪愝掕偟傑偡.
	 * 
	 * @param weixiu
	 *            weixiu
	 */
	public void setWeixiu(Blob weixiu) {
		this.weixiu = weixiu;
	}

	/**
	 * weixiu 傪庢摼偟傑偡.
	 * 
	 * @return weixiu
	 */
	public Blob getWeixiu() {
		return this.weixiu;
	}

	/**
	 * tuihuan 傪愝掕偟傑偡.
	 * 
	 * @param tuihuan
	 *            tuihuan
	 */
	public void setTuihuan(String tuihuan) {
		this.tuihuan = tuihuan;
	}

	/**
	 * tuihuan 傪庢摼偟傑偡.
	 * 
	 * @return tuihuan
	 */
	public String getTuihuan() {
		return this.tuihuan;
	}


}
